changes on deckorate_graphql module
wikirate/wikirate pull request #1517
Opened 2023-07-06 15:09 UTC by vasgat

- add filtering on different wikirate entities

2023-07-11 16:57 UTC, ethn requested changes
I know there's a lot here. We can set up a time to pair if that's best.

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/query.rb
> +        def subcardtype_field fieldname, type, codename = nil
this seems like it's identical to the cardtype field, no?  The only difference is that it won't handle the singular variant.

My guess is that there's not really a need for this method. But if there is, it should be articulated in a comment, eg above the method.

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/answer.rb
> +      subcardtype_field :source, Company, :source
Why is the type company here?

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/answer_value.rb
> +        begin
This looks very odd. Can you explain what's going on here in a code comment?

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/answer_value.rb
> +        begin
I would recommend writing tests for this method to make sure it's behaving the way you want it to.

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/answer_value.rb
> +        if input_value.is_a?(Float) or input_value.is_a?(Integer) or input_value.is_a?(BigDecimal) or input_value.is_a?(BigInt)
another way to write this is:

```
case input_value
when Float, Integer, BigDeckomal, BigInt
  input_value
else
  ...
```

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/answer_value.rb
> +          input_value.split(",")
I don't know if it's ever possible that input_value is not a string (and does not respond to split) but `input_value.to_s` includes ", ". If so this would fail

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/company.rb
> +      subcardtype_field :answer, Answer, :metric_answer
This seems a little funny. Normally `subcardtype_field` does a Card search, and card searches on answers are going to be very slow. Here we want to use a lookup search.

But the method "answers" below actually overrides the `answers` method defined by `subcardtype_field` that calls `card_search`, right? so what does it do?

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/query.rb
> +        def subcardtype_field fieldname, type, codename = nil
After studying this further, here's what I would say:
1. I don't think defining the singular and plural variants in one method makes sense. If we need them both, we can specify both.
2. I'm not sure where the singular variant is used, and as written it doesn't look like it would ever do anything useful
3. So I don't think `subcardtype_field` is useful, and if it has a use, the name doesn't help me understand it.
4. I don't think there's anything deckorate-specific here; this can all be in card-mod

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/query.rb
> +      cardtype_field :relationship, Relationship, :relationship_answer
We don't want these to be cardtype_fields.  But we could add something called lookup fields.  Arguably the code for that should live in a module in the lookup mod.

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/metric_category_filter_type.rb
> +      end
all these filter types are just using the same code over and over again. We could do this much more efficiently.

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/metric_category_filter_type.rb
> +      end
Also, there's code in the filters for each of these.

For example, this one is in `filter_metric_type_options` in 05_metric_search.rb. That's where these should be coming from.

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/company.rb
> +        ::Card::AnswerQuery.new(filter, {}, limit: limit, offset: offset).lookup_relation.all
I don't think this is what we want to do.  

The general pattern of cardtype fields is something like (instance)+(cardtype). So in this case, it might be something like `Apple Inc+answers`.  So we could generally get that card by doing something like `[object, :metric_answer].card`.  If we do it like that, then it automatically handles `filter[:company_id] = object.card_id`; that's already in the default query. If we do it this way, we have to redefine the `answers` method everywhere we have an answers field.

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/company.rb
> +        ::Card::AnswerQuery.new(filter, {}, limit: limit, offset: offset).lookup_relation.all
So, this is rough pseudocode, but it might look something like:
```
def lookup_search search_card, limit=10, offset=0, **filter
  query_hash = (filter || {}).merge search_card.query_hash
  search_card.query.new(query_hash, limit: limit, offset:offset).run
end
```

Then you can just call something like `lookup_search [object, :metric_answer].card`.

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/dataset.rb
> +      subcardtype_field :answer, Answer, :metric_answer
Again, these have to be written differently. They should be lookup table searches, not card table searches.

That's the reason they were written so awkwardly before, but we should be able to generalize it well.

2023-07-11 16:57 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/query.rb
> +              else
I think would generalize this by making sure all the filter types map directly to the filter keys and then doing something like

```
filter_type = const_get_if_defined const("#{filter.to_s.camelize}FilterType") || String
argument filter, filter_type, required: false
```

I think you could get rid of almost all of this that way.

2023-07-25 21:01 UTC, ethn requested changes
This is looking great. Please make sure it passes all the tests (including the code climate style tests) before merging.

2023-07-25 21:01 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/company_category_filter_type.rb
> +        value option.url_key, value: option
use `filter_company_category_options`

2023-07-25 21:01 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/deckorate_fields.rb
> +            filter_type = ENUM_FILTERS.include?(filter) ? GraphQL::Types.const_get("#{filter.to_s.camelize}FilterType"): String
I think the ENUM_FILTERS are the only part of this that are wikirate-specific, right? And I'm not sure it's necessary. You could just test whether the constant exists, no? (with `const_defined`)

If we did that, and if `card_field`, `cardtype_field`, `singular_field`, and `plural_field` were in the graphql mod, then I think they could be used by non-deckorate projects. And if lookup_field were in mod lookups (perhaps in a module named something like `Card::LookupGraphqlField`) then that could be used in non-deckorate projects with lookup fields.

I think you were trying to explain to me that you thought there was a reason it shouldn't be generalized, though? Can you explain?

2023-07-25 21:01 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/wikirate_card.rb
> +      end
You can just use `extend DeckorateFields`, and then you don't need `class << self`

2023-07-28 12:32 UTC, vasgat commented on mod/deckorate_graphql/lib/graph_q_l/types/company_category_filter_type.rb
> +        value option.url_key, value: option
There is an issue with the company categories on the test data. I am not sure why but it seems the content of the categories are something like A+A and I get the following error, if I use the generalize method: `filter_option_values(:metric, "company_category")` we developed: `Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 'A+A' does not`

2023-09-22 16:30 UTC, ethn requested changes
Please replace this PR with a request to the main branch. That will trigger all the testing that we want. 

It looks to me like an rspec is still failing.

2023-09-22 16:31 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/company_category_filter_type.rb
> +        value option.url_key, value: option
`:commons_company_category.card` is more concise and easier to read than `::Card.fetch(:commons_company_category)`

2023-09-22 16:33 UTC, ethn commented on mod/deckorate_graphql/lib/graph_q_l/types/deckorate_fields.rb
> +      end
did we decide not to move card_field and cardtype_field to the more general graphql module?

2023-09-25 14:00 UTC, ethn commented
@vasgat, whenever you're finished with the comments here, feel free to close this PR

2023-09-26 13:52 UTC, ethn commented
closing this one to avoid duplicate test runs on semaphore. The comments are, of course, still available if useful even if the PR is closed.

2023-09-26 13:52 UTC, closed without merging