Breadcrumbs
wikirate/wikirate pull request #1568
Opened 2023-11-22 01:38 UTC by cschweipert

Adds the link to the parent to breadcrumps if the breadcrumb has a parent and if the current card is the breadcrumb with the parent.

2023-11-22 02:51 UTC, cschweipert commented
This is work in progress. The tests revealed a bug.

2023-11-27 22:47 UTC, ethn requested changes
getting there! Just some very minor tweaks suggested

2023-11-27 22:47 UTC, ethn commented on mod/deckorate_datasets/set/type/dataset.rb
> +  def should_insert_parent_link?
more idiomatic just to say `#insert_parent_link?`

2023-11-27 22:47 UTC, ethn commented on mod/deckorate_datasets/set/type/dataset.rb
> +    card.parent != "" && card
I don't think card will ever be nil.

You could just do `card.parent.present?`

2023-11-27 22:47 UTC, ethn commented on mod/deckorate_datasets/set/type/dataset.rb
> +    ]
you could just say `breadcrumb_array = super`, right? Less duplication, more robust if the original method is edited?

2023-11-27 22:47 UTC, ethn commented on mod/deckorate_datasets/set/type/dataset.rb
> +include_set Abstract::Breadcrumbs
`Abstract::DeckorateTabbed` includes `Abstract::Header`, which includes `Abstract::Breadcrumbs`. So this is fine but not really necessary.

2023-11-29 15:50 UTC, ethn approved these changes
nice

2023-11-29 15:50 UTC, merged