Ux improvements 6
wikirate/wikirate pull request #624
Opened 2017-03-17 16:58 UTC by srivig

- Stylesheet cleanup
- Style fixes and tweaks on various pages 
-  Improved Project page 
    -  5,7 layout instead of 6,6 (for the better readability of company and project list) 
    - Display progress bar values on mouse hover on metric and company list (to declutter the list)
-  Responsive homepage, metric and company pages (only tested on screen emulators)
I still need to test all pages on staging or on dev since I removed large chunks of scss snippets

2017-03-17 19:40 UTC, xithan requested changes

2017-03-17 19:40 UTC, xithan commented on mod/profiles/set/right/report_search.rb
> +  view :wikirate_topic_list do
You have to override `sublist` not `list` otherwise you remove the subtabs.

2017-03-17 19:40 UTC, xithan commented on mod/profiles/set/right/report_search.rb
> +  view :metric_value_list do
Same issue here. You killed the subtabs by renaming this view.

2017-03-21 12:55 UTC, xithan requested changes
line 171 needs to be adjusted
`return if cardtype.in? [...]`

2017-03-22 19:59 UTC, xithan commented on mod/layout/set/abstract/media.rb
> +    opts[:media_opts] = {} unless opts[:media_opts]
<=> `opts[:media_opts] ||= {}`

2017-03-22 20:00 UTC, xithan approved these changes

2017-03-22 20:01 UTC, xithan requested changes
you have to change the button labels in the tests, too

2017-03-23 16:24 UTC, xithan approved these changes

2017-03-23 16:33 UTC, xithan requested changes

2017-03-23 16:33 UTC, xithan commented on mod/profiles/set/right/report_search.rb
> +    :wikirate_topic
:metric_value is missing

2017-03-23 16:54 UTC, srivig commented on mod/profiles/set/right/report_search.rb
> +    :wikirate_topic
added

2017-03-23 20:57 UTC, xithan approved these changes

2017-03-23 20:58 UTC, merged