posts and new tab titles
wikirate/wikirate pull request #804
Opened 2018-04-22 04:20 UTC by ethn

This adds posts as described here: https://www.pivotaltracker.com/story/show/156223859

It also standardizes tabs following the proposal I put out in slack:
> ALL TABS: 2 lines:
  top: count (optional) & icon (required)
  bottom: title (required) (edited)
To do this I had to pick some new icons, all of which are now represented alongside the old in a single icon map. I expect @srivig will want to review and improve:
1. the post pages 
2. the tab design
3.  the icons

I want to add some tests using philipp's new test API

2018-04-22 23:37 UTC, ethn commented on mod/wikirate/set/type/wikirate_topic/structure.rb
> +    %i[details wikirate_company post project]
tab lists are now actually just lists.

2018-04-22 23:42 UTC, ethn commented on mod/wikirate/set/all/wikirate/icons.rb
> +}.freeze
@srivig, this is the icon map.

2018-04-22 23:44 UTC, ethn commented on mod/posts/set/all/post.rb
> +  end
this post tab is here because it's the same for all types.  We might be able to repeat something like this pattern for other types.

2018-04-23 13:47 UTC, srivig commented on mod/layout/template/abstract/listing/listing.haml
> +  .listing-left.p-2.font-weight-bold{ class: "col-#{middle ? 6 : 8}" }
This change would break the responsiveness.

2018-04-25 22:35 UTC, xithan requested changes
I like the tab api improvements but I'm waiting for a test coverage greater than 0 before I approve this.

2018-04-27 17:11 UTC, ethn commented
over 50 (generic) specs added.

2018-04-27 18:57 UTC, xithan approved these changes
👍

2018-04-27 23:41 UTC, merged