industries (so far) and error handling
wikirate/wikirate pull request #885
Opened 2018-09-10 07:16 UTC by ethn

2018-09-11 10:05 UTC, xithan requested changes
"If it's not tested, it doesn't work"

2018-09-11 10:05 UTC, xithan commented on mod/metrics/set/abstract/value.rb
> +# end
seems like good api to me. Why is it commented?

2018-09-11 10:05 UTC, xithan commented on mod/metrics/set/type/free_text_value.rb
> +  end
that could be the default in `Abstract::Value`

2018-09-11 10:05 UTC, xithan commented on mod/metrics/set/type/metric/creation.rb
> +      type_code: value_cardtype_code
dot missing ?!

2018-09-11 10:05 UTC, xithan commented on mod/isic/spec/set/type/isic_class_value_spec.rb
> +
would be good to have at least one test that checks that pulling the options from json is working

2018-09-11 10:05 UTC, xithan commented on mod/metrics/set/type/metric/answers.rb
> +end
can we document somewhere what all these variants of compositions of "value", "code", and "type" mean and what kind of value they hold?

2018-09-11 10:08 UTC, xithan commented on mod/metrics/set/type/metric/creation.rb
> +      type_code: value_cardtype_code
probably correct this way

2018-09-11 10:53 UTC, ethn commented on mod/isic/spec/set/type/isic_class_value_spec.rb
> +
agree. all that code is now in decko, though.  will write it there.

2018-09-11 12:20 UTC, ethn commented on mod/metrics/set/abstract/value.rb
> +# end
I commented because it wasnt used.  but I restored it.

2018-09-11 14:32 UTC, ethn commented
The JSON options are now entirely handled (and lightly tested) in Decko.

2018-09-12 08:58 UTC, xithan approved these changes

2018-09-12 08:58 UTC, merged